# Generated by Django 6.0.3 on 2026-04-04 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='max_leads',
            new_name='monthly_price',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='price',
            new_name='setup_fee',
        ),
        migrations.AddField(
            model_name='team',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='team.plan'),
        ),
    ]
