# Generated by Django 6.0.3 on 2026-04-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_plan_max_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_leads',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
