# Generated by Django 6.0.3 on 2026-04-19 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_plan_max_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_members',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='team.plan'),
        ),
    ]
