# Generated by Django 6.0.3 on 2026-05-07 14:06

from datetime import datetime, time

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_team_membership_roles(apps, schema_editor):
    Team = apps.get_model('team', 'Team')
    TeamMembership = apps.get_model('team', 'TeamMembership')
    timezone = django.utils.timezone

    for team in Team.objects.select_related('created_by').all():
        owner_defaults = {
            'role': 'owner',
            'joined_at': timezone.make_aware(
                datetime.combine(team.created_at, time.min),
                timezone.get_current_timezone(),
            ),
        }
        owner_membership, created = TeamMembership.objects.get_or_create(
            team=team,
            user=team.created_by,
            defaults=owner_defaults,
        )

        updates = []
        if owner_membership.role != 'owner':
            owner_membership.role = 'owner'
            updates.append('role')
        if owner_membership.joined_at is None:
            owner_membership.joined_at = owner_defaults['joined_at']
            updates.append('joined_at')
        if updates:
            owner_membership.save(update_fields=updates)

        member_joined_at = owner_defaults['joined_at']
        TeamMembership.objects.filter(team=team, joined_at__isnull=True).exclude(
            pk=owner_membership.pk,
        ).update(joined_at=member_joined_at)
        TeamMembership.objects.filter(team=team).exclude(
            pk=owner_membership.pk,
        ).exclude(role='owner').update(role='member')


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_plan_max_members_alter_team_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE team_team_members ADD COLUMN role varchar(20) NOT NULL DEFAULT 'member'",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="ALTER TABLE team_team_members ADD COLUMN joined_at datetime NULL",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='TeamMembership',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20)),
                        ('joined_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                        ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='team.team')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'team_team_members',
                        'ordering': ('joined_at', 'id'),
                    },
                ),
                migrations.AlterField(
                    model_name='team',
                    name='members',
                    field=models.ManyToManyField(related_name='teams', through='team.TeamMembership', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.RunPython(backfill_team_membership_roles, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddConstraint(
                    model_name='teammembership',
                    constraint=models.UniqueConstraint(fields=('team', 'user'), name='unique_team_membership'),
                ),
            ],
        ),
    ]
