# Generated by Django 6.0.3 on 2026-05-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_teammembership_alter_team_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_advanced_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_email_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_export_tools',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='has_team_roles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_sessions_per_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_leads',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
