# Generated by Django 6.0.3 on 2026-05-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('notifications', '0002_notification_email_sent_notification_email_sent_at')]

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
